"""Patch application helpers backed by cphmd.native.system wrappers.

PatchApplier.apply_to_topology owns the MEMORY.md HSD/HSE rename-before-filter
invariant: histidines are converted to HSP before selected_residues filters
inspect the titratable list. Histidine PRES definitions use the Phase 9 Option C
path: a generated synthetic stream, because pyCHARMM has no direct
PRES-registration API. Arbitrary user/workflow stream files remain behind
cphmd.native.system.stream_file.
"""

from __future__ import annotations

import atexit
import os
import random
import shutil
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from cphmd.core.patch_spec import PATCH_REGISTRY, PatchSpec

_PATCH_STREAM_FILE_NAME = "his_patches_generated.str"
_PATCH_STREAM_DIR_PREFIX = "cphmd_patch_"
_PATCH_STREAM_STALE_SECONDS = 24 * 60 * 60
_PATCH_STREAM_CACHE_KEY: tuple[str, ...] | None = None
_PATCH_STREAM_PATH: Path | None = None
_PATCH_TMPDIRS: set[Path] = set()
_PATCH_TMPDIR_CLEANUP_REGISTERED = False


def _native_system():
    from cphmd.native import system

    return system


def _atom_selection(*, segid: str, resid: int | str):
    from cphmd.native.types import AtomSelection

    return AtomSelection(segid=segid, resid=resid)


def _format_charge(value: float) -> str:
    return f"{value:.5f}"


def _serialize_patchspec(spec: PatchSpec) -> str:
    comment = f" ! {spec.comment}" if spec.comment else ""
    lines = [f"PRES {spec.name} {_format_charge(spec.charge)}{comment}"]

    if spec.atom_types:
        atom_group_starts = set(spec.atom_group_starts)
        for index, atom_op in enumerate(spec.atom_types):
            if index == 0 or atom_op.atom_name in atom_group_starts:
                if not lines or lines[-1] != "GROUP":
                    lines.append("GROUP")
            if atom_op.atom_type is None or atom_op.charge is None:  # pragma: no cover
                raise ValueError(f"Patch '{spec.name}' has malformed atom type op")
            lines.append(
                f"ATOM {atom_op.atom_name} {atom_op.atom_type} {_format_charge(atom_op.charge)}"
            )

    for atom_op in spec.atom_deletes:
        lines.append(f"delete ATOM {atom_op.atom_name}")

    for atom_op in spec.atom_renames:
        lines.append(f"RENAME ATOM {atom_op.atom_name} {atom_op.new_name}")

    for bond_op in spec.bond_adds:
        lines.append(f"bond {bond_op.atoms[0]} {bond_op.atoms[1]}")

    for bond_op in spec.bond_deletes:
        lines.append(f"delete BOND {bond_op.atoms[0]} {bond_op.atoms[1]}")

    for double_atoms in spec.bond_doubles:
        lines.append(f"DOUBLE {' '.join(double_atoms)}")

    for improper_op in spec.improper_adds:
        lines.append(f"IMPR {' '.join(improper_op.atoms)}")

    for improper_op in spec.improper_deletes:
        lines.append(f"delete IMPR {' '.join(improper_op.atoms)}")

    for record in spec.ic_records:
        params = " ".join(_format_charge(value) for value in record.values)
        lines.append(f"IC {' '.join(record.atoms)} {params}")

    for donor_h, donor_heavy in spec.donors:
        lines.append(f"DONOR {donor_h} {donor_heavy}")

    for acceptor in spec.acceptors:
        lines.append(f"ACCEPTOR {acceptor}")

    return "\n".join(lines)


def _serialize_patch_stream(registry: dict[str, PatchSpec]) -> str:
    lines = [
        "read rtf card append",
        "* cphmd generated histidine patches",
        "* generated by cphmd.core.patch_applier",
        "*",
        "36  1",
    ]
    for spec in registry.values():
        lines.append(_serialize_patchspec(spec))
    lines.append("end")
    lines.append("")
    return "\n".join(lines)


def _remove_stale_patch_tmpdirs(tmp_root: Path, *, now: float | None = None) -> None:
    stale_before = (time.time() if now is None else now) - _PATCH_STREAM_STALE_SECONDS
    try:
        entries = tuple(tmp_root.iterdir())
    except OSError:
        return
    for entry in entries:
        if not entry.is_dir():
            continue
        if not entry.name.startswith(_PATCH_STREAM_DIR_PREFIX):
            continue
        try:
            mtime = entry.stat().st_mtime
        except OSError:
            continue
        if mtime >= stale_before:
            continue
        shutil.rmtree(entry, ignore_errors=True)


def _cleanup_patch_tmpdirs() -> None:
    for tmpdir in tuple(_PATCH_TMPDIRS):
        shutil.rmtree(tmpdir, ignore_errors=True)
        _PATCH_TMPDIRS.discard(tmpdir)


def _register_patch_tmpdir(tmpdir: Path) -> None:
    global _PATCH_TMPDIR_CLEANUP_REGISTERED
    _PATCH_TMPDIRS.add(tmpdir)
    if _PATCH_TMPDIR_CLEANUP_REGISTERED:
        return
    atexit.register(_cleanup_patch_tmpdirs)
    _PATCH_TMPDIR_CLEANUP_REGISTERED = True


def ensure_patches_streamed(*, force: bool = False) -> Path:
    global _PATCH_STREAM_CACHE_KEY
    global _PATCH_STREAM_PATH
    cache_key = tuple(_serialize_patchspec(spec) for spec in PATCH_REGISTRY.values())
    if _PATCH_STREAM_CACHE_KEY == cache_key and _PATCH_STREAM_PATH is not None:
        if _PATCH_STREAM_PATH.exists():
            if force:
                _native_system().stream_file(str(_PATCH_STREAM_PATH))
            return _PATCH_STREAM_PATH

    tmp_root = Path(os.environ.get("TMPDIR", tempfile.gettempdir()))
    _remove_stale_patch_tmpdirs(tmp_root)

    suffix = random.getrandbits(32)
    stream_dir = tmp_root / f"{_PATCH_STREAM_DIR_PREFIX}{os.getpid()}_{suffix}"
    stream_dir.mkdir(parents=True, exist_ok=False)
    _register_patch_tmpdir(stream_dir)

    stream_path = stream_dir / _PATCH_STREAM_FILE_NAME
    stream_path.write_text(_serialize_patch_stream(PATCH_REGISTRY), encoding="utf-8")

    try:
        _native_system().stream_file(str(stream_path))
    except Exception:
        shutil.rmtree(stream_dir, ignore_errors=True)
        _PATCH_TMPDIRS.discard(stream_dir)
        raise
    else:
        _PATCH_STREAM_CACHE_KEY = cache_key
        _PATCH_STREAM_PATH = stream_path
        return stream_path


@dataclass(frozen=True)
class PatchApplyResult:
    patch_name: str
    segid: str
    resid: int | str
    source_resname: str
    target_resname: str
    charmm_calls: tuple[str, ...]


class PatchApplier:
    def __init__(self, registry: dict[str, PatchSpec] | None = None) -> None:
        self._registry = dict(PATCH_REGISTRY if registry is None else registry)

    def apply_to_residue(
        self,
        segid: str,
        resid: int | str,
        current_resname: str,
        *,
        patch_name: str | None = None,
    ) -> PatchApplyResult:
        match_context: dict[str, Any] = {"segid": segid, "resid": resid}
        spec = self._resolve_spec(current_resname, patch_name, **match_context)
        charmm_calls = tuple(self._emit(spec, segid, resid))
        return PatchApplyResult(
            patch_name=spec.name,
            segid=segid,
            resid=resid,
            source_resname=current_resname,
            target_resname=spec.target_resname,
            charmm_calls=charmm_calls,
        )

    def apply_to_topology(
        self,
        *,
        candidate_resnames: frozenset[str],
        segid_filter: str | None = None,
    ) -> tuple[PatchApplyResult, ...]:
        system = _native_system()
        snapshot = system.get_topology_snapshot()
        residues = getattr(snapshot, "residues", None)

        if residues:
            discovered = tuple(residues)
        else:
            discovered = []
            seen_atom_keys: set[tuple[str, int | str]] = set()
            for atom in snapshot.atoms:
                key = (atom.segid, atom.resid)
                if key in seen_atom_keys:
                    continue
                seen_atom_keys.add(key)
                discovered.append(atom)

        discovered_candidates: list[tuple[str, int | str, str]] = []
        seen_candidates: set[tuple[str, int | str]] = set()
        for residue in discovered:
            if residue.resname not in candidate_resnames:
                continue
            if segid_filter is not None and residue.segid != segid_filter:
                continue
            key = (residue.segid, residue.resid)
            if key in seen_candidates:
                continue
            seen_candidates.add(key)
            discovered_candidates.append((residue.segid, residue.resid, residue.resname))

        resolved_candidates: list[tuple[str, int | str, str, PatchSpec]] = []
        for segid, resid, resname in discovered_candidates:
            spec = self._resolve_spec(resname, None, segid=segid, resid=resid)
            resolved_candidates.append((segid, resid, resname, spec))

        results: list[PatchApplyResult] = []
        for segid, resid, resname, spec in resolved_candidates:
            charmm_calls = tuple(self._emit(spec, segid, resid))
            results.append(
                PatchApplyResult(
                    patch_name=spec.name,
                    segid=segid,
                    resid=resid,
                    source_resname=resname,
                    target_resname=spec.target_resname,
                    charmm_calls=charmm_calls,
                )
            )
        return tuple(results)

    def _resolve_spec(
        self,
        current_resname: str,
        patch_name: str | None,
        **match_context: Any,
    ) -> PatchSpec:
        if patch_name is not None:
            try:
                spec = self._registry[patch_name]
            except KeyError as exc:
                raise KeyError(f"Patch '{patch_name}' is not registered") from exc
            if not spec.matches(current_resname, **match_context):
                raise ValueError(
                    f"Patch '{patch_name}' does not apply to residue '{current_resname}'"
                )
            return spec

        matches: list[tuple[int, int, PatchSpec]] = []
        for index, spec in enumerate(self._registry.values()):
            if spec.matches(current_resname, **match_context):
                matches.append((spec.priority, index, spec))
        matches.sort(key=lambda item: (item[0], item[1]))

        if not matches:
            raise ValueError(f"No patch registered for residue '{current_resname}'")
        if len(matches) > 1:
            candidate_names = ", ".join(spec.name for _, _, spec in matches)
            raise ValueError(
                "Multiple patches match residue "
                f"'{current_resname}' ({candidate_names}); pass patch_name explicitly"
            )
        return matches[0][2]

    def _emit(self, spec: PatchSpec, segid: str, resid: int | str) -> list[str]:
        system = _native_system()
        selection = _atom_selection(segid=segid, resid=resid)
        patch_call = f"patch(patch_name={spec.name!r}, segid={segid!r}, resid={resid!r})"
        rename_call = (
            "rename_residues("
            f"selection=AtomSelection(segid={segid!r}, resid={resid!r}), "
            f"new_resname={spec.target_resname!r})"
        )

        if spec.rename_order == "before_patch":
            system.rename_residues(selection, spec.target_resname)
            system.patch(spec.name, segid, resid)
            return [rename_call, patch_call]
        if spec.rename_order == "after_patch":
            system.patch(spec.name, segid, resid)
            system.rename_residues(selection, spec.target_resname)
            return [patch_call, rename_call]
        raise ValueError(f"Invalid rename_order '{spec.rename_order}' for patch '{spec.name}'")


__all__ = [
    "PatchApplyResult",
    "PatchApplier",
    "_serialize_patchspec",
    "ensure_patches_streamed",
]
